a = 97
b = 98
c = 99
d = 100
e = 101
f = 102
g = 103
h = 104
i = 105
j = 106
k = 107
l = 108
m = 109
n = 110
o = 111
p = 112
q = 113
r = 114
s = 115
t = 116
u = 117
v = 118
w = 119
x = 120
y = 121
z = 122
print(f'{a} e {chr(a)}')
print(f'{b} e {chr(b)}')
print(f'{c} e {chr(c)}')
print(f'{d} e {chr(d)}')
print(f'{e} e {chr(e)}')
print(f'{f} e {chr(f)}')
print(f'{g} e {chr(g)}')
print(f'{h} e {chr(h)}')
print(f'{i} e {chr(i)}')
print(f'{j} e {chr(j)}')
print(f'{k} e {chr(k)}')
print(f'{l} e {chr(l)}')
print(f'{m} e {chr(m)}')
print(f'{n} e {chr(n)}')
print(f'{o} e {chr(o)}')
print(f'{p} e {chr(p)}')
print(f'{q} e {chr(q)}')
print(f'{r} e {chr(r)}')
print(f'{s} e {chr(s)}')
print(f'{t} e {chr(t)}')
print(f'{u} e {chr(u)}')
print(f'{v} e {chr(v)}')
print(f'{w} e {chr(w)}')
print(f'{x} e {chr(x)}')
print(f'{y} e {chr(y)}')
print(f'{z} e {chr(z)}')
